### ISSUE TITLE
fails to compile with hoauth2 >= 2.6.0

### ISSUE THREAD

**Issue by stuebinm** [freckle/yesod-auth-oauth2#164]
`yesod-auth-oauth2-0.7.0.2` fails to build with `hoauth2` 2.6.0 (or newer). Build output:

 ```
Failed to build yesod-auth-oauth2-0.7.0.2.
Build log (
/home/stuebinm/.cabal/logs/ghc-8.10.7/yesod-auth-oauth2-0.7.0.2-ef249bb1bc58a20b711a5007f9f39cd2121205d9475321350438e6ed5d9e7ed8.log
):
Configuring library for yesod-auth-oauth2-0.7.0.2..
Preprocessing library for yesod-auth-oauth2-0.7.0.2..
Building library for yesod-auth-oauth2-0.7.0.2..
[ 1 of 27] Compiling Network.OAuth.OAuth2.Compat ( src/Network/OAuth/OAuth2/Compat.hs, dist/build/Network/OAuth/OAuth2/Compat.o, dist/build/Network/OAuth/OAuth2/Compat.dyn_o )

src/Network/OAuth/OAuth2/Compat.hs:21:7: error:
    Module ‘Network.OAuth.OAuth2’ does not export ‘OAuth2Error’
   |
21 |     , OAuth2Error
   |       ^^^^^^^^^^^

src/Network/OAuth/OAuth2/Compat.hs:26:43: error:
    Module ‘Network.OAuth.OAuth2.TokenRequest’ does not export ‘Errors’
   |
26 | import Network.OAuth.OAuth2.TokenRequest (Errors)
   |                                           ^^^^^^
Error: cabal: Failed to build yesod-auth-oauth2-0.7.0.2
```

**Comment by pbrisbin** [comment]
Thanks for the report, I'll work on this this week.

**Comment by mjgpy3** [comment]
Looks like our [nightly stack yaml is passing](https://github.com/freckle/yesod-auth-oauth2/actions/runs/4046718754/jobs/6959861959). I'm assuming this means the error is just for compat with 2.7.0.

I'll bump our nightly and continue investigating!
